import { renderMarkdown } from "@/src/lib/content/markdown";

/**
 * Typography for HTML produced by `renderMarkdown`.
 *
 * The content is generated by our own escape-first renderer, which is why a
 * `dangerouslySetInnerHTML` sink is acceptable here and nowhere else. Never
 * point this component at a string that did not come from `renderMarkdown`.
 */
const PROSE_CLASSES = [
  "max-w-none text-base leading-7 text-foreground/90",
  "[&_a]:font-medium [&_a]:text-primary [&_a]:underline [&_a]:underline-offset-4",
  "[&_blockquote]:border-l-2 [&_blockquote]:border-primary/60 [&_blockquote]:pl-5 [&_blockquote]:font-serif [&_blockquote]:text-xl [&_blockquote]:italic",
  "[&_code]:rounded [&_code]:bg-secondary [&_code]:px-1.5 [&_code]:py-0.5 [&_code]:font-mono [&_code]:text-sm",
  "[&_h1]:mt-0 [&_h1]:mb-5 [&_h1]:font-serif [&_h1]:text-4xl [&_h1]:tracking-[-0.03em]",
  "[&_h2]:mt-12 [&_h2]:mb-4 [&_h2]:font-serif [&_h2]:text-3xl [&_h2]:tracking-[-0.025em]",
  "[&_h3]:mt-8 [&_h3]:mb-3 [&_h3]:font-serif [&_h3]:text-2xl [&_h3]:tracking-[-0.02em]",
  "[&_h4]:mt-6 [&_h4]:mb-2 [&_h4]:font-semibold [&_h4]:text-lg",
  "[&_hr]:my-10 [&_hr]:border-foreground/20",
  "[&_img]:my-6 [&_img]:w-full [&_img]:rounded-lg [&_img]:border [&_img]:border-foreground/15",
  "[&_li]:mt-2 [&_li]:pl-1 [&_li]:marker:text-primary",
  "[&_ol]:my-4 [&_ol]:list-decimal [&_ol]:pl-6",
  "[&_p]:mt-4 [&_p]:first:mt-0",
  "[&_pre]:mt-5 [&_pre]:overflow-x-auto [&_pre]:rounded-lg [&_pre]:border [&_pre]:border-foreground/15 [&_pre]:bg-secondary/60 [&_pre]:p-4",
  "[&_pre_code]:bg-transparent [&_pre_code]:p-0 [&_pre_code]:text-sm",
  "[&_ul]:my-4 [&_ul]:list-disc [&_ul]:pl-6",
].join(" ");

export function Prose({
  markdown,
  idPrefix,
}: {
  markdown: string;
  /**
   * Optional namespace for the heading ids this fragment emits. Pass it when
   * several documents are rendered into one page, so a heading id cannot
   * repeat across them or shadow an ancestor's `id` anchor.
   */
  idPrefix?: string;
}) {
  return (
    <div
      className={PROSE_CLASSES}
      dangerouslySetInnerHTML={{
        __html: renderMarkdown(markdown, { idPrefix }),
      }}
    />
  );
}
